---
- name: Using the uri module to connect to tower
  hosts: tower
  gather_facts: false

  tasks:
    - name: Copy the existing New template using the uri module
      uri:
        url: ...
        validate_certs: no
        method: ...
        return_content: yes
        force_basic_auth: yes
        user: ...
        password: ...
        status_code: [201, 202]
        body:
          name: ...
        body_format: json

...
